on: [push, pull_request]
name: flake8_py3


jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        if: github.event_name == 'push'
        with:
          python-version: 3.7.9
          architecture: x64
      - name: Checkout PyTorch
        uses: actions/checkout@master
        if: github.event_name == 'push'
      - name: Install flake8
        if: github.event_name == 'push'
        run: pip install flake8
      - name: Run flake8
        uses: suo/flake8-github-action@releases/v1
        if: github.event_name == 'push'
        with:
          checkName: 'flake8_py3'   # NOTE: this needs to be the same as the job name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
      - uses: actions/checkout@v1
        if: github.event_name == 'pull_request'
      - uses: grantmcconnaughey/lintly-flake8-github-action@v1.0
        if: github.event_name == 'pull_request'
        with:
          # The GitHub API token to create reviews with
          token: ${{ secrets.GITHUB_TOKEN }}
          # Fail if "new" violations detected or "any", default "new"
          failIf: new
          # Additional arguments to pass to flake8, default "." (current directory)
          args: "--ignore=E121,E123 ."
